### ISSUE TITLE
Entitiy is nil when working with NSManagedObject subclass in Swift 

### ISSUE THREAD

**Issue by fruitcoder** [Wasappli/WACoreDataSpotlight#1]
Thank you for your amazing library, I could get CoreSpotlight running in 3mins! The only thing I noticed is that `objectFromUserActivity:` crashed, because 
`[NSEntityDescription entityForName:NSStringFromClass(mapping.objectClass)
                                                              inManagedObjectContext:self.managedObjectContext];`
returns nil. After short Investigation I found out that NSStringFromClass returns _ModuleName_._ClassName_ and, therefore, I don't a valid Entity. I couldn't find a nice solution so I just fixed it in my code.

**Comment by ipodishima** [comment]
Hi,

Sorry for the delay, just had some vacations ;)
What do you mean with `ModuleName` ?
