### ISSUE TITLE
How to delete an item from the indexer?

### ISSUE THREAD

**Issue by acerbetti** [Wasappli/WACoreDataSpotlight#2]
I can only see the insert and update, is it possible to add the delete as well ?

Thanks for your hard work

**Comment by ipodishima** [comment]
Hi,

Thank you ;)
For the deletion, you only have to remove the object from the db and it will disappear from the index as well. I did not exposed the method to delete from the index.
If you do not want to add an item to the index, you can do so though

**Comment by mbjacks** [comment]
@ipodishima 

There is a use case where for security reasons you would want to delete the searchable index, but not remove data from the database.  You may want to consider exposing a method to remove all indexed items.

Thank you as well for you work!
